<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByTitle ($title) {
        $query = $this->createQueryBuilder('p')
            ->where('p.title LIKE :title')
            ->setParameter('title', '%'.$title.'%')
            ->orderBy('p.title', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

}
