parameters:
    my_mailer.class:     AppBundle\Services\SendMail
#    my_mailer.transport: '@mailer'

services:
    app.admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Post }

    my_mailer:
        class:       "%my_mailer.class%"
#        arguments:   ["%my_mailer.transport%"]
